steps:
  # Build the container image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=$_DOCKER_PKG/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--cache=true'
      - '--cache-ttl=6h'
      - '--build-arg=_NEXT_PUBLIC_ENV1=$_NEXT_PUBLIC_ENV1'
      - '--build-arg=_NEXT_PUBLIC_ENV2=$_NEXT_PUBLIC_ENV2'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - $_SERVICE_NAME
      - '--image'
      - '$_DOCKER_PKG/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'

substitutions:
  _DOCKER_PKG: asia-northeast1-docker.pkg.dev
  _REPO_NAME: docker-repo
